### ISSUE TITLE
Bug in books Songs, Obadiah and Philemon

### ISSUE THREAD

**Issue by MrMesquita** [seven1m/bible_api#100]
The book of Song of Solomon in the Almeida translation is not localized, and the book of Obadiah only returns one verse

if you use https://bible-api.com/sng1 works.
and if you use https://bible-api.com/sng1?translation=almeida also works.

but, if you use https://bible-api.com/Cânticos1?translation=almeida, don´t find anything.

Obadiah: https://bible-api.com/Obadias1?translation=almeida just return an only verse. the same happens in filemon

**Comment by seven1m** [comment]
https://bible-api.com/Cânticos1?translation=almeida works now. Very sorry about that. This was a bug I fixed in the book name regex here: https://github.com/seven1m/bible_ref/commit/6b66c7f75510bf2cd833bfb5d1c9fa66de1e9326

As for the other books with only a single chapter, please see: #94.

**Comment by seven1m** [comment]
FYI I added a note to the site about single-chapter books and an option to change the matching behavior. Please see the section "Single-Chapter Books" on the site here: https://bible-api.com
