### ISSUE TITLE
Random verses api

### ISSUE THREAD

**Issue by shedrack-okunda** [seven1m/bible_api#107]
I am trying to call the random verse api and it does not return a thing in the browser

**Comment by seven1m** [comment]
Is this the URL you are using? 

https://bible-api.com/?random=verse

**Comment by shedrack-okunda** [comment]
yes this one

**Comment by seven1m** [comment]
OK, what happens when you use that URL? Do you get an error? Can you include a screenshot?

**Comment by shedrack-okunda** [comment]
I will do so actually what it does is this in post man it returns random
verses but in the browser it is not returning anything that is when i put
it in a try and catch it returns the error message

**Comment by seven1m** [comment]
Oh, I see the problem. We are not including the CORS header for this endpoint. I will fix this...

**Comment by seven1m** [comment]
This should work for you now!

**Comment by shedrack-okunda** [comment]
You have already fixed the CORS problem

**Comment by seven1m** [comment]
I don't understand what you mean. I did indeed fix the CORS problem. Can you verify your original issue is now fixed?

**Comment by shedrack-okunda** [comment]
Thank you
Let me verify and i will let you know
