### ISSUE TITLE
Errors installing dependencies - racc & mysql2

### ISSUE THREAD

**Issue by squidsworld** [seven1m/bible_api#111]
Firstly - thank you for creating this extremely useful tool. It is a major component of a bible tool I am programming. I am about to make that tool public, and so I don't want to unfairly burden your api server which I have been testing on thus far.

Apologies - I am not familiar with the ruby ecosystem and its dependency management tools (gem?). Following the instructions in the readme was enough to get me oriented but I had to follow some errors to get it going. Namely, when I get to the "bundle install" command, it fails, telling me that "An error occurred while installing racc"

The solution I found was this:
**I needed to install "ruby-dev" (ruby package) and do "apt install build-essentials" to get gcc in order to build rake.** 

This starting point for this was on a fresh ubuntu-server 24.04 environment - with only the software from the instructions installed. The only exception is that I chose to use mariadb instead of mysql. (mariadb, ruby, and redis installed)

**Errors with racc installation:**
If a person does not have gcc installed, racc will not install successfully. Not technically an issue with your software, so I apologize if raising an issue is inappropriate - I just wanted to share this information on the git repo so that it can help in case someone else runs into this exact problem.

**Errors with mysql2 installation**
After installing racc successfully, I began getting errors about "an error occurred while installing mysql2 (0.5.5)" - I needed to do "apt install libmariadb-dev" in order to get that to work.

Once both of these dependencies were handled, the "bundle install"  command successfully installed the package. It may be worth noting that I did manually run the "gem install" commands for racc and mysql2 packages as the error messages suggested, as opposed to handling the other dependencies and just re-running "bundle install" - I don't know if that was necessary or if just running "bundle install" again would have been fine. Noted in case it matters.

**Comment by seven1m** [comment]
Thanks for sharing your experience. Let me know if you are having any further issues!
