### ISSUE TITLE
Jude returns only the first verse

### ISSUE THREAD

**Issue by AkashSaggar** [seven1m/bible_api#25]
When I go on the URL [https://bible-api.com/Jude+1](https://bible-api.com/Jude+1), it only returns the first verse.
This happens even if I specify a verse number, such as Jude+1:5, it will still return verse 1.
But, if I specify a range of verses like Jude+1:5-20, it works as expected.

**Comment by seven1m** [comment]
Thanks for the report. Jude is a tricky onensince there is only a single chapter and you need not specify it. 

This works: http://bible-api.com/Jude+1-25

I’ll seenif I can tweak the parser so it recognizes what you posted...

**Comment by seven1m** [comment]
FYI I added a note to the site about single-chapter books and an option to change the matching behavior. Please see the section "Single-Chapter Books" on the site here: https://bible-api.com
