### ISSUE TITLE
Your API..

### ISSUE THREAD

**Issue by x1705** [seven1m/bible_api#28]
Hi, i want to try and use your bible API.. 
i often have to text many different ways before I settle on one.
I would like you to know that ahead of time in case you receive a "more than common"
amount of 'hits' on your API.. it is probably just me. :)

my IP is 173.22.0.102

I mention this not only as a courtesy, but also because since last night i cannot get it to respond.
(thinking maybe I was Banned?)  anyways, much appreciate your work on this.. I am very new to 'programming', so that is a reason why it may appear i am 'over using' your API.. lol

Thanks again.
Garrett.
garrettskro@gmail.com

**Comment by seven1m** [comment]
@x1705 thanks for the heads up. I have not banned your IP and have not banned any IPs recently for that matter. Can you tell me what response you get from the API currently?

**Comment by x1705** [comment]
Hi Tim, nice to meet you.. fortunatley it was a typo on my part.  It seems
to be functioning just fine, (at least your end).
I'm still learning how to do this. lol :)

I hope my "pings" don't intrude.. nonetheless, feel free to let me know..

I am working on a Facebook BibleBot.  I have a very nice working one that
is currently (still) waiting a review from them.
it takes forever it seems.. but i really like your API better than the one
i am using now, for various possible reasons.

i am trying to get the JSON to display correctly on My end at the moment..
its a challenge.. lol  for me at least.
but as all things are.. a good work in progress.

Will let you know further if i encounter any errors from your side.. (which
i doubt).

Thanks for making this available!

All the best Tim.
-Garrett.

**Comment by seven1m** [comment]
Great, glad it's working for you again. I love hearing that people are finding good use of the service. Best of luck and God bless!
