### ISSUE TITLE
Deuterocanon requires OSIS ID for KJV

### ISSUE THREAD

**Issue by sb057** [seven1m/bible_api#36]
http://bible-api.com/tobit+1:1
`{"error":"not found"}`

http://bible-api.com/tob+1:1
`{"reference":"Tobit 1:1","verses":[{"book_id":"TOB","book_name":"Tobit","chapter":1,"verse":1,"text":"The book of the words of Tobit, the son of Tobiel, the son of Ananiel, the son of Aduel, the son of Gabael, of the seed of Asiel, of the tribe of Naphtali;\n"}],"text":"The book of the words of Tobit, the son of Tobiel, the son of Ananiel, the son of Aduel, the son of Gabael, of the seed of Asiel, of the tribe of Naphtali;\n","translation_id":"web","translation_name":"World English Bible","translation_note":"Public Domain"}`

http://bible-api.com/judith+1:1
`{"reference":"Jude 1","verses":[{"book_id":"JUD","book_name":"Jude","chapter":1,"verse":1,"text":"Jude, a servant of Jesus Christ, and brother of James, to those who are called, sanctified by God the Father, and kept for Jesus Christ:\n"}],"text":"Jude, a servant of Jesus Christ, and brother of James, to those who are called, sanctified by God the Father, and kept for Jesus Christ:\n","translation_id":"web","translation_name":"World English Bible","translation_note":"Public Domain"}`

http://bible-api.com/jdt+1:1
`{"reference":"Judith 1:1","verses":[{"book_id":"JDT","book_name":"Judith","chapter":1,"verse":1,"text":"In the twelfth year of the reign of Nebuchadnezzar, who reigned over the Assyrians in Nineveh, the great city, in the days of Arphaxad, who reigned over the Medes in Ecbatana,\n"}],"text":"In the twelfth year of the reign of Nebuchadnezzar, who reigned over the Assyrians in Nineveh, the great city, in the days of Arphaxad, who reigned over the Medes in Ecbatana,\n","translation_id":"web","translation_name":"World English Bible","translation_note":"Public Domain"}`

**Comment by seven1m** [comment]
Thanks for the issue. We can tweak the regex list here: https://github.com/seven1m/bible_ref/blob/master/lib/bible_ref/languages/english.rb

**Comment by seven1m** [comment]
This fix has been deployed to bible-api.com.
