### ISSUE TITLE
Random verses

### ISSUE THREAD

**Issue by CaioBianchi** [seven1m/bible_api#38]
Hi there,

Thank you for making this API available.
I just went through the source code, and I was wondering if querying a random verse / book and displaying it in an endpoint such as `/random` or something like that is something that has been considered (?).
This should be a fairly simple feature to implement, and I'd be happy to submit a PR if it hasn't been done already.

Cheers!

**Comment by bonniesimon** [comment]
This would be awesome if implemented.

**Comment by seven1m** [comment]
I would accept a PR to add a `bible-api.com/?random=verse` endpoint. Note I think it should be a URL param (after the question mark) rather than a path -- that's so it doesn't live in the same namespace as book/chapter/reference URLs.

**Comment by xslendix** [comment]
You can close this issue now
