### ISSUE TITLE
Serverless, CDN, Caching, and SQLite.

### ISSUE THREAD

**Issue by michaelsoliman-com** [seven1m/bible_api#39]
Add Cloudflare (CDN) to provide caching and https for the api. Makes it faster, reduces the load on the server, and makes it secure.

Also try to host it as a lambda function (make it serverless). The project is using MySql which is over engineering for a read only access. May be the api can read from the xml files directly or preload the verses into an sqlite database. 

That will reduce the hosting and maintenance costs to practically zero.

**Comment by seven1m** [comment]
This is not a bug. Thanks for your input though!
