### ISSUE TITLE
Incorrect newline in Revelation 22:21

### ISSUE THREAD

**Issue by mikjakrych** [seven1m/bible_api#41]
When [querying for rev22:21 in KJV](http://bible-api.com/rev22:21?translation=kjv), bible_api incorrectly places a line break in the middle of the verse.

Thank you for this API. Keep up the noble work, and God bless you.

**Comment by seven1m** [comment]
I think this is the same problem as #32, but I'll leave the issue open so we can check that it's fixed when we get around to fixing #32. Thanks!

**Comment by seven1m** [comment]
On second thought, let's just make a list on #32. Closing this...
