### ISSUE TITLE
Whitespace in front of John 3:16

### ISSUE THREAD

**Issue by mikjakrych** [seven1m/bible_api#42]
Bible_api returns [John 3:16 in the default translation](https://bible-api.com/jn%203:16) correctly, but [in KJV](https://bible-api.com/jn%203:16?translation=kjv), there are a bunch of whitespace characters prepended to the text.

**Comment by seven1m** [comment]
Again, probably same as #32. We don't fix issues in the text individually--it will be a change in the way we import the text from the XML. I'm going to close this issue as we ha e enough examples already. Thanks!
