### ISSUE TITLE
"Mk" not linked to "Mark"

### ISSUE THREAD

**Issue by mikjakrych** [seven1m/bible_api#43]
"Mk" is a common abbreviation for the Gospel of Mark (according to [Logos](https://www.logos.com/bible-book-abbreviations)), but Bible_API does not return results that query for "Mk."

**Comment by seven1m** [comment]
Thanks for the issue. We can tweak the regex list here: https://github.com/seven1m/bible_ref/blob/master/lib/bible_ref/languages/english.rb
