### ISSUE TITLE
Multiple parameters

### ISSUE THREAD

**Issue by EmmanuelQC** [seven1m/bible_api#47]
Hello Tim! Really loving this API! 

Is there any way to include multiple parameters for a query?
eg. `https://bible-api.com/john%203:16,5:1-5?verse_numbers=true` and `?translation=kjv`

Maybe `https://bible-api.com/john%203:16,5:1-5?verse_numbers=true,translation=kjv` or another way
It would be awesome if you could make this possible when you have the time!

God bless!

**Comment by seven1m** [comment]
Thanks!

Sure, you can use the `&` to join more than one parameter, e.g. https://bible-api.com/john%203:16,5:1-5?verse_numbers=true&translation=kjv

**Comment by EmmanuelQC** [comment]
Thanks for the quick reply!
Can't believe I didn't think of that. God bless!
