### ISSUE TITLE
Json no aplicativo 

### ISSUE THREAD

**Issue by Warleywasy** [seven1m/bible_api#50]
Estou tentando colocar a bíblia no Excel do Google na seção script da planinha, onde podemos colocar o código.

Eu precisa de um auxilio se fosso possível

**Comment by seven1m** [comment]
This is what I got from Google Translate:

>I'm trying to put the bible in Google's Excel in the script section of the plan, where we can put the code.
>
>I need assistance if possible 

Sorry, I don't provide support for helping to write your application code. You will need to hire a contractor to do that part. The API just provides the data for your own code to fetch.

Good luck!

**Comment by htadashi** [comment]
Hi @Warleywasy 

I am Google Apps Script developer. Recently, I just made a integration between Google Docs and bible-api.com.
Please take a look on this gist: https://gist.github.com/htadashi/991c4c5be166c04d44daf1d3dc55c8e1

If you want any help, do not hesitate to contact me. This information is on my personal website: https://htadashi.github.io/

In Portuguese:

> Olá @Warleywasy ,
> 
> Eu sou um desenvolvedor de Google Apps Script. Recentemente, eu fiz uma integração entre Google Docs e o bible-api.com.
> Favor dar uma olhada nesse link: https://gist.github.com/htadashi/991c4c5be166c04d44daf1d3dc55c8e1
> 
> Qualquer coisa, não hesite em me contatar. Minha informação de contato está no meu site pessoal: https://htadashi.github.io/


P.S.: @seven1m  Hope you don't mind I sharing my Gist in this already closed issue. Couldn't find other way to contact him.

**Comment by Warleywasy** [comment]
Boa tarde!

Se puder ajudar...eu sei que o que eu estou fazendo está errado. Não sei
montar a função no google.

Enviei um arquivo em anexo

Em seg., 8 de mar. de 2021 às 19:30, Tadashi <notifications@github.com>
escreveu:
