### ISSUE TITLE
Hosting Yourself is Broken

### ISSUE THREAD

**Issue by croeber** [seven1m/bible_api#57]
I would like to host this myself because I want to integrate a bible into my recovery android app. When I go through the steps to host it myself, it is failing saying this?

fatal: clone of 'git@github.com:churchio/open-bibles.git' into submodule path...

At this step 

**git submodule update --init**

Is this hosted on in a private repo? Can you provide the SQL scripts?

**Comment by seven1m** [comment]
Sorry about that. That old URL was where the repo used to live. Fixed now.
