### ISSUE TITLE
Philippians Doesn't Grab the Book

### ISSUE THREAD

**Issue by MasterTemple** [seven1m/bible_api#59]
I have tested with several books of the Bible and when I do something like the following `https://bible-api.com/John1`, `https://bible-api.com/John%201`, `https://bible-api.com/john1`, `https://bible-api.com/john%201`, `https://bible-api.com/John 1`, or even `https://bible-api.com/john 1`, and I get the entire chapter. However, when I make similar calls with Philippians I just get one verse. For example, what would normally give me Philippians 3, will give me Philippians 1:3 instead. Thank you for your time.

**Comment by seven1m** [comment]
Thanks for the bug report. This was fixed in 0c2053717448986868d27879e5c3a8e069588f31.
