### ISSUE TITLE
bible-api.com seems down

### ISSUE THREAD

**Issue by tim-hub** [seven1m/bible_api#60]
in Australia, I could not visit it

**Comment by seven1m** [comment]
Thanks for letting me know. I'll get some monitoring on that.

**Comment by billpetro** [comment]
I too am having problems.

Installed
Enabled
Selected KJV
Opened new note
Typed "--John 1:1"
Selected it

Then nothing happens

<img width="557" alt="BillPetro_-_Obsidian_v0_13_24" src="https://user-images.githubusercontent.com/561093/152698325-224ecee9-099b-4078-8c55-1ea395f67894.png">
.

**Comment by seven1m** [comment]
What app is that? (The API is up btw)

**Comment by billpetro** [comment]
Cockpit error on my part. I had a space between John and 1:1.

BTW, is there a way to get a chapter at a time? 

Example: `john1` would place the entire text of John chapter 1 into obsidian.

**Comment by tim-hub** [comment]
> Cockpit error on my part. I had a space between John and 1:1.
> 
> BTW, is there a way to get a chapter at a time?
> 
> Example: `--john1` would place the entire text of John chapter 1 into obsidian.

Hi @billpetro 

Are you using [Obisidian Bible Reference plugin](https://github.com/tim-hub/obsidian-bible-reference)

If so it would be great if you create issues here
https://github.com/tim-hub/obsidian-bible-reference/issues
or discussion here.

https://github.com/tim-hub/obsidian-bible-reference/discussions

**Comment by billpetro** [comment]
tim-hub, yes, I'm using the Obsidian Bible Reference plugin. I'll direct my comments to the locations you mentioned.
