### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by juanpumpkinpie** [seven1m/bible_api#67]
Hey, stunning work by the way. Just wonder how many request can I do in order to dont' be blocked in IP. the documentation doesn't mentioned the rank and I don't know how to make the linux server for myselft, thanks

**Comment by seven1m** [comment]
I can't say for sure. There isn't a hard limit. I just keep an eye on the server to make sure no one is slowing it down too much.

I'd prefer not to block anyone!
