### ISSUE TITLE
Document the randomverse endpoint

### ISSUE THREAD

**Issue by myselfhimself** [seven1m/bible_api#69]
Hello,
thank you for this project!
It would be nice to document the random verse endpoint in the following places:
- [ ] on https://bible-api.com/
- [ ] in this project's README

**Comment by myselfhimself** [comment]
Background info: a random verse endpoint was added in pull request https://github.com/seven1m/bible_api/pull/46

Test URL:
https://bible-api.com/?random=verse

**Comment by seven1m** [comment]
Good idea. If you want to make a PR for this, I will merge.

**Comment by seven1m** [comment]
I did this awhile back and forgot to close the issue.
