### ISSUE TITLE
Create a gh extension for bible_api?

### ISSUE THREAD

**Issue by myselfhimself** [seven1m/bible_api#70]
Hello,
following [gh inspire](https://github.com/lakuapik/gh-inspire) there could be a random verse command relying on the [random verse endpoint](https://github.com/seven1m/bible_api/issues/69) of the bible_api project for the [Github CLI tool](https://cli.github.com/).
Just an idea :)

**Comment by myselfhimself** [comment]
The `gh inspire` tool is a shell script which could be forked. It uses `jq` as a dependency... The Bible API's reponses are in JSON, so the latter command would make sense as well.

**Comment by seven1m** [comment]
That's a cool idea! I don't have time to implement it myself, unfortunately. But I have been wanting to make a wiki page listing projects that use bible-api. Let me know if you end up making this!
