### ISSUE TITLE
Difficulty with Book names

### ISSUE THREAD

**Issue by brendawall** [seven1m/bible_api#83]
Sorry guys I'm really dumb. I'm trying to reference Corinthians using the API but no spelling of Corinthians works

**Comment by seven1m** [comment]
https://bible-api.com/i+corinthians+1:1

https://bible-api.com/1+corinthians+1:1

https://bible-api.com/1+cor+1:1

https://bible-api.com/ii+cor+1:1

Those work for me.  What have you tried that didn't work?

**Comment by brendawall** [comment]
Thanks so much, sorry I forgot to put the number at the beginning
