### ISSUE TITLE
Missing dutch translation and error handling.

### ISSUE THREAD

**Issue by JasperTheMinecraftDev** [seven1m/bible_api#92]
Hey Tim!

I tried using the new dutch translation on your site(https://bible-api.com) but it looks like the website went down after I tried to use the translation. I've noticed that the dutch translation isn't in the table on the website aswell.
Can you add the translation and some proper error handling to avoid this issue?

Wish you the best,
Jasper

**Comment by seven1m** [comment]
I fixed the bug that kept breaking the site. I will update the translations database on the live site when I get time.
