### ISSUE TITLE
Single chapter books

### ISSUE THREAD

**Issue by arthurogunfiye** [seven1m/bible_api#94]
I tried to get single chapter books like Obadiah, Philemon, Jude etc but only got the first verse.

I tried the name of the book alone e.g. https://bible-api.com/jude

I tried the name of the book and 1 e.g. https://bible-api.com/jude%201

I tried other things but nothing worked.

Would you be so kind as to look into this issue please?

Thank you.

**Comment by seven1m** [comment]
I'm sorry, but I don't have a great solution for this that works for everyone. More details in this comment: https://github.com/seven1m/bible_api/issues/51#issuecomment-799456431

Returning the whole chapter when just the book name is given could work... 🤔

**Comment by arthurogunfiye** [comment]
Thank you for responding @seven1m. I appreciate and commend the time and effort you put into implementing this API.

**Comment by seven1m** [comment]
FYI I added a note to the site about single-chapter books and an option to change the matching behavior. Please see the section "Single-Chapter Books" on the site here: https://bible-api.com
